open! Core_kernel

module Table = Hashtbl.Make (struct
  type t = Items.t * Game.t [@@deriving sexp, compare, hash]
end)

let compute blob =
  let b64 =
    match Base64.encode ~pad:true blob with
    | Ok x -> x
    | Error (`Msg msg) -> failwith msg
  in
  sprintf "data:image/png;base64,%s" b64

let dubious = lazy ([%blob "images/dubious.png"] |> compute)

let cache = Table.create ()

let get item game =
  Table.find_or_add cache (item, game) ~default:(fun () ->
      let blob =
        match item, game with
        | Palm_fruit, _ -> [%blob "images/palm-fruit.png"]
        | Apple, _ -> [%blob "images/apple.png"]
        | Wildberry, _ -> [%blob "images/wildberry.png"]
        | Hylian_shroom, _ -> [%blob "images/hylian-shroom.png"]
        | Hyrule_herb, _ -> [%blob "images/hyrule-herb.png"]
        | Hyrule_bass, _ -> [%blob "images/hyrule-bass.png"]
        | Sanke_carp, _ -> [%blob "images/sanke-carp.png"]
        | Raw_gourmet_meat, _ -> [%blob "images/raw-gourmet-meat.png"]
        | Raw_whole_bird, _ -> [%blob "images/raw-whole-bird.png"]
        | Raw_prime_meat, _ -> [%blob "images/raw-prime-meat.png"]
        | Raw_bird_thigh, _ -> [%blob "images/raw-bird-thigh.png"]
        | Raw_meat, _ -> [%blob "images/raw-meat.png"]
        | Raw_bird_drumstick, _ -> [%blob "images/raw-bird-drumstick.png"]
        | Bird_egg, _ -> [%blob "images/bird-egg.png"]
        | Fresh_milk, _ -> [%blob "images/fresh-milk.png"]
        | Acorn, _ -> [%blob "images/acorn.png"]
        | Chickaloo_tree_nut, _ -> [%blob "images/chickaloo-tree-nut.png"]
        | Hylian_rice, _ -> [%blob "images/hylian-rice.png"]
        | Tabantha_wheat, _ -> [%blob "images/tabantha-wheat.png"]
        | Cane_sugar, _ -> [%blob "images/cane-sugar.png"]
        | Goat_butter, _ -> [%blob "images/goat-butter.png"]
        | Goron_spice, _ -> [%blob "images/goron-spice.png"]
        | Rock_salt, _ -> [%blob "images/rock-salt.png"]
        | Hearty_truffle, _ -> [%blob "images/hearty-truffle.png"]
        | Hearty_bass, _ -> [%blob "images/hearty-bass.png"]
        | Hearty_radish, _ -> [%blob "images/hearty-radish.png"]
        | Hearty_blueshell_snail, _ -> [%blob "images/hearty-blueshell-snail.png"]
        | Hearty_durian, _ -> [%blob "images/hearty-durian.png"]
        | Big_hearty_truffle, _ -> [%blob "images/big-hearty-truffle.png"]
        | Hearty_salmon, _ -> [%blob "images/hearty-salmon.png"]
        | Hearty_lizard, _ -> [%blob "images/hearty-lizard.png"]
        | Big_hearty_radish, _ -> [%blob "images/big-hearty-radish.png"]
        | Stamella_shroom, _ -> [%blob "images/stamella-shroom.png"]
        | Restless_cricket, _ -> [%blob "images/restless-cricket.png"]
        | Courser_bee_honey, _ -> [%blob "images/courser-bee-honey.png"]
        | Bright_eyed_crab, _ -> [%blob "images/bright-eyed-crab.png"]
        | Staminoka_bass, _ -> [%blob "images/staminoka-bass.png"]
        | Energetic_rhino_beetle, _ -> [%blob "images/energetic-rhino-beetle.png"]
        | Endura_shroom, _ -> [%blob "images/endura-shroom.png"]
        | Tireless_frog, _ -> [%blob "images/tireless-frog.png"]
        | Endura_carrot, _ -> [%blob "images/endura-carrot.png"]
        | Spicy_pepper, _ -> [%blob "images/spicy-pepper.png"]
        | Warm_safflina, _ -> [%blob "images/warm-safflina.png"]
        | Summerwing_butterfly, _ -> [%blob "images/summerwing-butterfly.png"]
        | Sunshroom, _ -> [%blob "images/sunshroom.png"]
        | Warm_darner, _ -> [%blob "images/warm-darner.png"]
        | Sizzlefin_trout, _ -> [%blob "images/sizzlefin-trout.png"]
        | Hydromelon, _ -> [%blob "images/hydromelon.png"]
        | Cool_safflina, _ -> [%blob "images/cool-safflina.png"]
        | Winterwing_butterfly, _ -> [%blob "images/winterwing-butterfly.png"]
        | Chillshroom, _ -> [%blob "images/chillshroom.png"]
        | Cold_darner, _ -> [%blob "images/cold-darner.png"]
        | Chillfin_trout, _ -> [%blob "images/chillfin-trout.png"]
        | Voltfruit, _ -> [%blob "images/voltfruit.png"]
        | Electric_safflina, _ -> [%blob "images/electric-safflina.png"]
        | Thunderwing_butterfly, _ -> [%blob "images/thunderwing-butterfly.png"]
        | Zapshroom, _ -> [%blob "images/zapshroom.png"]
        | Electric_darner, _ -> [%blob "images/electric-darner.png"]
        | Voltfin_trout, _ -> [%blob "images/voltfin-trout.png"]
        | Fireproof_lizard, _ -> [%blob "images/fireproof-lizard.png"]
        | Smotherwing_butterfly, _ -> [%blob "images/smotherwing-butterfly.png"]
        | Rushroom, _ -> [%blob "images/rushroom.png"]
        | Swift_carrot, _ -> [%blob "images/swift-carrot.png"]
        | Hightail_lizard, _ -> [%blob "images/hightail-lizard.png"]
        | Fleet_lotus_seeds, _ -> [%blob "images/fleet-lotus-seeds.png"]
        | Swift_violet, _ -> [%blob "images/swift-violet.png"]
        | Hot_footed_frog, _ -> [%blob "images/hot-footed-frog.png"]
        | Blue_nightshade, _ -> [%blob "images/blue-nightshade.png"]
        | Sneaky_river_snail, _ -> [%blob "images/sneaky-river-snail.png"]
        | Sunset_firefly, _ -> [%blob "images/sunset-firefly.png"]
        | Silent_shroom, _ -> [%blob "images/silent-shroom.png"]
        | Stealthfin_trout, _ -> [%blob "images/stealthfin-trout.png"]
        | Silent_princess, _ -> [%blob "images/silent-princess.png"]
        | Mighty_thistle, _ -> [%blob "images/mighty-thistle.png"]
        | Bladed_rhino_beetle, _ -> [%blob "images/bladed-rhino-beetle.png"]
        | Mighty_bananas, _ -> [%blob "images/mighty-bananas.png"]
        | Razorshroom, _ -> [%blob "images/razorshroom.png"]
        | Mighty_carp, _ -> [%blob "images/mighty-carp.png"]
        | Razorclaw_crab, _ -> [%blob "images/razorclaw-crab.png"]
        | Mighty_porgy, _ -> [%blob "images/mighty-porgy.png"]
        | Armoranth, _ -> [%blob "images/armoranth.png"]
        | Rugged_rhino_beetle, _ -> [%blob "images/rugged-rhino-beetle.png"]
        | Fortified_pumpkin, _ -> [%blob "images/fortified-pumpkin.png"]
        | Ironshroom, _ -> [%blob "images/ironshroom.png"]
        | Armored_carp, _ -> [%blob "images/armored-carp.png"]
        | Ironshell_crab, _ -> [%blob "images/ironshell-crab.png"]
        | Armored_porgy, _ -> [%blob "images/armored-porgy.png"]
        | Fairy, _ -> [%blob "images/fairy.png"]
        | Star_fragment, _ -> [%blob "images/star-fragment.png"]
        | Monster_horn Bokoblin_horn, BOTW -> [%blob "images/bokoblin-horn-botw.png"]
        | Monster_horn Bokoblin_horn, TOTK -> [%blob "images/bokoblin-horn-totk.png"]
        | Monster_horn Moblin_horn, BOTW -> [%blob "images/moblin-horn-botw.png"]
        | Monster_horn Moblin_horn, TOTK -> [%blob "images/moblin-horn-totk.png"]
        | Monster_horn Lizalfos_horn, BOTW -> [%blob "images/lizalfos-horn-botw.png"]
        | Monster_horn Lizalfos_horn, TOTK -> [%blob "images/lizalfos-horn-totk.png"]
        | Monster_horn Lynel_horn, _ -> [%blob "images/lynel-horn.png"]
        | Monster_horn Hinox_toenail, _ -> [%blob "images/hinox-toenail.png"]
        | Monster_horn Keese_wing, _ -> [%blob "images/keese-wing.png"]
        | Monster_horn Chuchu_jelly, _ -> [%blob "images/chuchu-jelly.png"]
        | Monster_horn Octorok_tentacle, _ -> [%blob "images/octorok-tentacle.png"]
        | Monster_horn Octo_balloon, _ -> [%blob "images/octo-balloon.png"]
        | Monster_horn Ancient_screw, _ -> [%blob "images/ancient-screw.png"]
        | Monster_horn Ancient_spring, _ -> [%blob "images/ancient-spring.png"]
        | Monster_horn Gibdo_bone, _ -> [%blob "images/gibdo-bone.png"]
        | Monster_horn Gibdo_wing, _ -> [%blob "images/gibdo-wing.png"]
        | Monster_horn Horriblin_horn, _ -> [%blob "images/horriblin-horn.png"]
        | Monster_horn Blue_bokoblin_horn, _ -> [%blob "images/blue-bokoblin-horn.png"]
        | Monster_horn Black_bokoblin_horn, _ -> [%blob "images/black-bokoblin-horn.png"]
        | Monster_horn Blue_horriblin_horn, _ -> [%blob "images/blue-horriblin-horn.png"]
        | Monster_horn Black_horriblin_horn, _ -> [%blob "images/black-horriblin-horn.png"]
        | Monster_horn Blue_moblin_horn, _ -> [%blob "images/blue-moblin-horn.png"]
        | Monster_horn Black_moblin_horn, _ -> [%blob "images/black-moblin-horn.png"]
        | Monster_horn Electric_lizalfos_horn, _ -> [%blob "images/electric-lizalfos-horn.png"]
        | Monster_horn Fire_breath_lizalfos_horn, _ -> [%blob "images/fire-breath-lizalfos-horn.png"]
        | Monster_horn Ice_breath_lizalfos_horn, _ -> [%blob "images/ice-breath-lizalfos-horn.png"]
        | Monster_horn Blue_lizalfos_horn, _ -> [%blob "images/blue-lizalfos-horn.png"]
        | Monster_horn Black_lizalfos_horn, _ -> [%blob "images/black-lizalfos-horn.png"]
        | Monster_horn Aerocuda_wing, _ -> [%blob "images/aerocuda-wing.png"]
        | Monster_fang Bokoblin_fang, _ -> [%blob "images/bokoblin-fang.png"]
        | Monster_fang Moblin_fang, _ -> [%blob "images/moblin-fang.png"]
        | Monster_fang Lizalfos_talon, _ -> [%blob "images/lizalfos-talon.png"]
        | Monster_fang Lynel_hoof, _ -> [%blob "images/lynel-hoof.png"]
        | Monster_fang Hinox_tooth, _ -> [%blob "images/hinox-tooth.png"]
        | Monster_fang Molduga_fin, _ -> [%blob "images/molduga-fin.png"]
        | Monster_fang White_chuchu_jelly, _ -> [%blob "images/white-chuchu-jelly.png"]
        | Monster_fang Red_chuchu_jelly, _ -> [%blob "images/red-chuchu-jelly.png"]
        | Monster_fang Yellow_chuchu_jelly, _ -> [%blob "images/yellow-chuchu-jelly.png"]
        | Monster_fang Octorok_eyeball, _ -> [%blob "images/octorok-eyeball.png"]
        | Monster_fang Ice_keese_wing, _ -> [%blob "images/ice-keese-wing.png"]
        | Monster_fang Fire_keese_wing, _ -> [%blob "images/fire-keese-wing.png"]
        | Monster_fang Electric_keese_wing, _ -> [%blob "images/electric-keese-wing.png"]
        | Monster_fang Ancient_gear, _ -> [%blob "images/ancient-gear.png"]
        | Monster_fang Ancient_shaft, _ -> [%blob "images/ancient-shaft.png"]
        | Monster_fang Gibdo_guts, _ -> [%blob "images/gibdo-guts.png"]
        | Monster_fang Horriblin_claw, _ -> [%blob "images/horriblin-claw.png"]
        | Monster_fang Aerocuda_eyeball, _ -> [%blob "images/aerocuda-eyeball.png"]
        | Monster_fang Fire_keese_eyeball, _ -> [%blob "images/fire-keese-eyeball.png"]
        | Monster_fang Ice_keese_eyeball, _ -> [%blob "images/ice-keese-eyeball.png"]
        | Monster_fang Electric_keese_eyeball, _ -> [%blob "images/electric-keese-eyeball.png"]
        | Monster_fang Like_like_stone, _ -> [%blob "images/like-like-stone.png"]
        | Monster_fang Fire_like_stone, _ -> [%blob "images/fire-like-stone.png"]
        | Monster_fang Ice_like_stone, _ -> [%blob "images/ice-like-stone.png"]
        | Monster_fang Shock_like_stone, _ -> [%blob "images/shock-like-stone.png"]
        | Monster_guts Bokoblin_guts, _ -> [%blob "images/bokoblin-guts.png"]
        | Monster_guts Moblin_guts, _ -> [%blob "images/moblin-guts.png"]
        | Monster_guts Lizalfos_tail, _ -> [%blob "images/lizalfos-tail.png"]
        | Monster_guts Lynel_guts, _ -> [%blob "images/lynel-guts.png"]
        | Monster_guts Hinox_guts, _ -> [%blob "images/hinox-guts.png"]
        | Monster_guts Molduga_guts, _ -> [%blob "images/molduga-guts.png"]
        | Monster_guts Keese_eyeball, _ -> [%blob "images/keese-eyeball.png"]
        | Monster_guts Icy_lizalfos_tail, _ -> [%blob "images/icy-lizalfos-tail.png"]
        | Monster_guts Red_lizalfos_tail, _ -> [%blob "images/red-lizalfos-tail.png"]
        | Monster_guts Yellow_lizalfos_tail, _ -> [%blob "images/yellow-lizalfos-tail.png"]
        | Monster_guts Ancient_core, _ -> [%blob "images/ancient-core.png"]
        | Monster_guts Giant_ancient_core, _ -> [%blob "images/giant-ancient-core.png"]
        | Monster_guts Horriblin_guts, _ -> [%blob "images/horriblin-guts.png"]
        | Monster_guts Electric_lizalfos_tail, _ -> [%blob "images/electric-lizalfos-tail.png"]
        | Monster_guts Fire_breath_lizalfos_tail, _ -> [%blob "images/fire-breath-lizalfos-tail.png"]
        | Monster_guts Ice_breath_lizalfos_tail, _ -> [%blob "images/ice-breath-lizalfos-tail.png"]
        | Monster_guts Blue_lizalfos_tail, _ -> [%blob "images/blue-lizalfos-tail.png"]
        | Monster_guts Black_lizalfos_tail, _ -> [%blob "images/black-lizalfos-tail.png"]
        | Dragon_scales Dinraal, _ -> [%blob "images/dinraal-scale.png"]
        | Dragon_scales Naydra, _ -> [%blob "images/naydra-scale.png"]
        | Dragon_scales Farosh, _ -> [%blob "images/farosh-scale.png"]
        | Dragon_claws Dinraal, _ -> [%blob "images/dinraal-claw.png"]
        | Dragon_claws Naydra, _ -> [%blob "images/naydra-claw.png"]
        | Dragon_claws Farosh, _ -> [%blob "images/farosh-claw.png"]
        | Dragon_fangs Dinraal, _ -> [%blob "images/dinraal-fang.png"]
        | Dragon_fangs Naydra, _ -> [%blob "images/naydra-fang.png"]
        | Dragon_fangs Farosh, _ -> [%blob "images/farosh-fang.png"]
        | Dragon_horns Dinraal, BOTW -> [%blob "images/dinraal-horn-botw.png"]
        | Dragon_horns Dinraal, TOTK -> [%blob "images/dinraal-horn-totk.png"]
        | Dragon_horns Naydra, BOTW -> [%blob "images/naydra-horn-botw.png"]
        | Dragon_horns Naydra, TOTK -> [%blob "images/naydra-horn-totk.png"]
        | Dragon_horns Farosh, BOTW -> [%blob "images/farosh-horn-botw.png"]
        | Dragon_horns Farosh, TOTK -> [%blob "images/farosh-horn-totk.png"]
        | Skyshroom, _ -> [%blob "images/skyshroom.png"]
        | Dazzlefruit, _ -> [%blob "images/dazzlefruit.png"]
        | Korok_frond, _ -> [%blob "images/korok-frond.png"]
        | Ancient_arowana, _ -> [%blob "images/ancient-arowana.png"]
        | Hylian_tomato, _ -> [%blob "images/hylian-tomato.png"]
        | Golden_apple, _ -> [%blob "images/golden-apple.png"]
        | Hateno_cheese, _ -> [%blob "images/hateno-cheese.png"]
        | Oil_jar, _ -> [%blob "images/oil-jar.png"]
        | Sun_pumpkin, _ -> [%blob "images/sun-pumpkin.png"]
        | Sundelion, _ -> [%blob "images/sundelion.png"]
        | Stambulb, _ -> [%blob "images/stambulb.png"]
        | Splash_fruit, _ -> [%blob "images/splash-fruit.png"]
        | Deep_firefly, _ -> [%blob "images/deep-firefly.png"]
        | Glowing_cave_fish, _ -> [%blob "images/glowing-cave-fish.png"]
        | Brightcap, _ -> [%blob "images/brightcap.png"]
        | Sticky_lizard, _ -> [%blob "images/sticky-lizard.png"]
        | Sticky_frog, _ -> [%blob "images/sticky-frog.png"]
      in
      compute blob)
