open! Core_kernel
open Items

let compute blob =
  let b64 =
    match Base64.encode ~pad:true blob with
    | Ok x -> x
    | Error (`Msg msg) -> failwith msg
  in
  sprintf "data:image/png;base64,%s" b64

let dubious = lazy ([%blob "images/dubious.png"] |> compute)

let blobs =
  List.fold all ~init:Map.empty ~f:(fun acc key ->
      let blob =
        match key with
        | Palm_fruit -> [%blob "images/2.png"]
        | Apple -> [%blob "images/3.png"]
        | Wildberry -> [%blob "images/4.png"]
        | Hylian_shroom -> [%blob "images/12.png"]
        | Hyrule_herb -> [%blob "images/25.png"]
        | Hyrule_bass -> [%blob "images/69.png"]
        | Sanke_carp -> [%blob "images/77.png"]
        | Raw_gourmet_meat -> [%blob "images/36.png"]
        | Raw_whole_bird -> [%blob "images/37.png"]
        | Raw_prime_meat -> [%blob "images/38.png"]
        | Raw_bird_thigh -> [%blob "images/39.png"]
        | Raw_meat -> [%blob "images/40.png"]
        | Raw_bird_drumstick -> [%blob "images/41.png"]
        | Bird_egg -> [%blob "images/46.png"]
        | Fresh_milk -> [%blob "images/48.png"]
        | Acorn -> [%blob "images/44.png"]
        | Chickaloo_tree_nut -> [%blob "images/45.png"]
        | Hylian_rice -> [%blob "images/43.png"]
        | Tabantha_wheat -> [%blob "images/47.png"]
        | Cane_sugar -> [%blob "images/49.png"]
        | Goat_butter -> [%blob "images/50.png"]
        | Goron_spice -> [%blob "images/51.png"]
        | Rock_salt -> [%blob "images/52.png"]
        | Hearty_truffle -> [%blob "images/11.png"]
        | Hearty_bass -> [%blob "images/68.png"]
        | Hearty_radish -> [%blob "images/23.png"]
        | Hearty_blueshell_snail -> [%blob "images/81.png"]
        | Hearty_durian -> [%blob "images/1.png"]
        | Big_hearty_truffle -> [%blob "images/10.png"]
        | Hearty_salmon -> [%blob "images/67.png"]
        | Hearty_lizard -> [%blob "images/101.png"]
        | Big_hearty_radish -> [%blob "images/22.png"]
        | Stamella_shroom -> [%blob "images/14.png"]
        | Restless_cricket -> [%blob "images/93.png"]
        | Courser_bee_honey -> [%blob "images/42.png"]
        | Bright_eyed_crab -> [%blob "images/84.png"]
        | Staminoka_bass -> [%blob "images/70.png"]
        | Energetic_rhino_beetle -> [%blob "images/96.png"]
        | Endura_shroom -> [%blob "images/13.png"]
        | Tireless_frog -> [%blob "images/99.png"]
        | Endura_carrot -> [%blob "images/24.png"]
        | Spicy_pepper -> [%blob "images/6.png"]
        | Warm_safflina -> [%blob "images/29.png"]
        | Summerwing_butterfly -> [%blob "images/87.png"]
        | Sunshroom -> [%blob "images/16.png"]
        | Warm_darner -> [%blob "images/91.png"]
        | Sizzlefin_trout -> [%blob "images/72.png"]
        | Hydromelon -> [%blob "images/5.png"]
        | Cool_safflina -> [%blob "images/28.png"]
        | Winterwing_butterfly -> [%blob "images/86.png"]
        | Chillshroom -> [%blob "images/15.png"]
        | Cold_darner -> [%blob "images/90.png"]
        | Chillfin_trout -> [%blob "images/71.png"]
        | Voltfruit -> [%blob "images/7.png"]
        | Electric_safflina -> [%blob "images/30.png"]
        | Thunderwing_butterfly -> [%blob "images/88.png"]
        | Zapshroom -> [%blob "images/17.png"]
        | Electric_darner -> [%blob "images/92.png"]
        | Voltfin_trout -> [%blob "images/73.png"]
        | Fireproof_lizard -> [%blob "images/102.png"]
        | Smotherwing_butterfly -> [%blob "images/89.png"]
        | Rushroom -> [%blob "images/18.png"]
        | Swift_carrot -> [%blob "images/26.png"]
        | Hightail_lizard -> [%blob "images/100.png"]
        | Fleet_lotus_seeds -> [%blob "images/8.png"]
        | Swift_violet -> [%blob "images/31.png"]
        | Hot_footed_frog -> [%blob "images/98.png"]
        | Blue_nightshade -> [%blob "images/34.png"]
        | Sneaky_river_snail -> [%blob "images/80.png"]
        | Sunset_firefly -> [%blob "images/97.png"]
        | Silent_shroom -> [%blob "images/21.png"]
        | Stealthfin_trout -> [%blob "images/74.png"]
        | Silent_princess -> [%blob "images/35.png"]
        | Mighty_thistle -> [%blob "images/32.png"]
        | Bladed_rhino_beetle -> [%blob "images/94.png"]
        | Mighty_bananas -> [%blob "images/9.png"]
        | Razorshroom -> [%blob "images/19.png"]
        | Mighty_carp -> [%blob "images/75.png"]
        | Razorclaw_crab -> [%blob "images/82.png"]
        | Mighty_porgy -> [%blob "images/78.png"]
        | Armoranth -> [%blob "images/33.png"]
        | Rugged_rhino_beetle -> [%blob "images/95.png"]
        | Fortified_pumpkin -> [%blob "images/27.png"]
        | Ironshroom -> [%blob "images/20.png"]
        | Armored_carp -> [%blob "images/76.png"]
        | Ironshell_crab -> [%blob "images/83.png"]
        | Armored_porgy -> [%blob "images/79.png"]
        | Fairy -> [%blob "images/85.png"]
        | Star_fragment -> [%blob "images/54.png"]
        | Monster_horn Bokoblin_horn -> [%blob "images/111.png"]
        | Monster_horn Moblin_horn -> [%blob "images/114.png"]
        | Monster_horn Lizalfos_horn -> [%blob "images/117.png"]
        | Monster_horn Lynel_horn -> [%blob "images/123.png"]
        | Monster_horn Hinox_toenail -> [%blob "images/140.png"]
        | Monster_horn Keese_wing -> [%blob "images/130.png"]
        | Monster_horn Chuchu_jelly -> [%blob "images/126.png"]
        | Monster_horn Octorok_tentacle -> [%blob "images/135.png"]
        | Monster_horn Octo_balloon -> [%blob "images/137.png"]
        | Monster_horn Ancient_screw -> [%blob "images/143.png"]
        | Monster_horn Ancient_spring -> [%blob "images/144.png"]
        | Monster_fang Bokoblin_fang -> [%blob "images/112.png"]
        | Monster_fang Moblin_fang -> [%blob "images/115.png"]
        | Monster_fang Lizalfos_talon -> [%blob "images/118.png"]
        | Monster_fang Lynel_hoof -> [%blob "images/124.png"]
        | Monster_fang Hinox_tooth -> [%blob "images/141.png"]
        | Monster_fang Molduga_fin -> [%blob "images/138.png"]
        | Monster_fang White_chuchu_jelly -> [%blob "images/127.png"]
        | Monster_fang Red_chuchu_jelly -> [%blob "images/128.png"]
        | Monster_fang Yellow_chuchu_jelly -> [%blob "images/129.png"]
        | Monster_fang Octorok_eyeball -> [%blob "images/136.png"]
        | Monster_fang Ice_keese_wing -> [%blob "images/131.png"]
        | Monster_fang Fire_keese_wing -> [%blob "images/132.png"]
        | Monster_fang Electric_keese_wing -> [%blob "images/133.png"]
        | Monster_fang Ancient_gear -> [%blob "images/145.png"]
        | Monster_fang Ancient_shaft -> [%blob "images/146.png"]
        | Monster_guts Bokoblin_guts -> [%blob "images/113.png"]
        | Monster_guts Moblin_guts -> [%blob "images/116.png"]
        | Monster_guts Lizalfos_tail -> [%blob "images/119.png"]
        | Monster_guts Lynel_guts -> [%blob "images/125.png"]
        | Monster_guts Hinox_guts -> [%blob "images/142.png"]
        | Monster_guts Molduga_guts -> [%blob "images/139.png"]
        | Monster_guts Keese_eyeball -> [%blob "images/134.png"]
        | Monster_guts Icy_lizalfos_tail -> [%blob "images/120.png"]
        | Monster_guts Red_lizalfos_tail -> [%blob "images/121.png"]
        | Monster_guts Yellow_lizalfos_tail -> [%blob "images/122.png"]
        | Monster_guts Ancient_core -> [%blob "images/147.png"]
        | Monster_guts Giant_ancient_core -> [%blob "images/148.png"]
        | Dragon_scales Dinraal -> [%blob "images/55.png"]
        | Dragon_scales Naydra -> [%blob "images/59.png"]
        | Dragon_scales Farosh -> [%blob "images/63.png"]
        | Dragon_claws Dinraal -> [%blob "images/56.png"]
        | Dragon_claws Naydra -> [%blob "images/60.png"]
        | Dragon_claws Farosh -> [%blob "images/64.png"]
        | Dragon_fangs Dinraal -> [%blob "images/57.png"]
        | Dragon_fangs Naydra -> [%blob "images/61.png"]
        | Dragon_fangs Farosh -> [%blob "images/65.png"]
        | Dragon_horns Dinraal -> [%blob "images/58.png"]
        | Dragon_horns Naydra -> [%blob "images/62.png"]
        | Dragon_horns Farosh -> [%blob "images/66.png"]
        | Skyshroom -> [%blob "images/skyshroom.png"]
        | Dazzlefruit -> [%blob "images/dazzlefruit.png"]
        | Korok_frond -> [%blob "images/korok-frond.png"]
        | Ancient_arowana -> [%blob "images/ancient-arowana.png"]
        | Hylian_tomato -> [%blob "images/hylian-tomato.png"]
        | Golden_apple -> [%blob "images/golden-apple.png"]
        | Hateno_cheese -> [%blob "images/hateno-cheese.png"]
        | Oil_jar -> [%blob "images/oil-jar.png"]
        | Sun_pumpkin -> [%blob "images/sun-pumpkin.png"]
        | Sundelion -> [%blob "images/sundelion.png"]
        | Stambulb -> [%blob "images/stambulb.png"]
        | Splash_fruit -> [%blob "images/splash-fruit.png"]
        | Deep_firefly -> [%blob "images/deep-firefly.png"]
        | Glowing_cave_fish -> [%blob "images/glowing-cave-fish.png"]
        | Brightcap -> [%blob "images/brightcap.png"]
        | Sticky_lizard -> [%blob "images/sticky-lizard.png"]
        | Sticky_frog -> [%blob "images/sticky-frog.png"]
      in
      Map.add_exn acc ~key ~data:(compute blob))
